---
title: "My-First-Blog"
date: 2022-08-03
---


title: Git Hub Club
author: Dinuk Dilshan
theme: minima
email: dilshan.lk47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn how to use Git at your workplace to keep your codebase safe and up-to-date, as well as how to collaborate with other developers on a team.

# social links
github_username:  DiNo47-lk

show_excerpts: true # set to false to remove excerpts on the homepage
